"""
Same-load conversion (engine/equivalence.py): the Naismith / Langmuir time
model recovers known parameters, the EP fallback, the design inverse, the
leave-one-out backtest harness and the method choice, the grade-cost hook,
and the API. Synthetic samples only (the real-data backtest is realdata/test_real_equivalence.py).
"""
import random

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from backend.engine import equivalence as E
from backend.engine.algorithms import minetti as M

AET = 140.0
V, VAM = 7.0, 600.0                   # the synthetic athlete: 7 km/h flat, 600 m/h up


def naismith_min(km, gain, loss=None):
    loss = gain if loss is None else loss
    return (km / V + gain / VAM + E.descent_hours(km, gain, loss)) * 60.0


def road(n=6, hr=135.0):
    return [E.Sample(f"2026-06-{i + 1:02d}", "road", 5.0, 20.0, 20.0, 5.0 / V * 60.0, hr) for i in range(n)]


def trails(n=8, noise=0.0, seed=1):
    rnd = random.Random(seed)
    out = []
    for i in range(n):
        km, gain = 3.0 + i, 150.0 + 70.0 * i
        t = naismith_min(km, gain) * (1 + rnd.uniform(-noise, noise))
        out.append(E.Sample(f"2026-07-{i + 1:02d}", "trail", km, gain, gain, t, 132.0))
    return out


def test_descent_follows_langmuir():
    assert E.descent_hours(10.0, 0.0, 0.0) == 0.0
    assert E.descent_hours(10.0, 200.0, 200.0) == 0.0                 # ~2.3 deg: no correction
    gentle = E.descent_hours(5.0, 300.0, 300.0)                        # ~6.8 deg
    steep = E.descent_hours(2.0, 500.0, 500.0)                         # ~26.6 deg
    assert gentle == pytest.approx(-10 / 60)                           # -10 min per 300 m
    assert steep == pytest.approx(500 / 300 * 10 / 60)                # +10 min per 300 m


def test_fit_recovers_the_synthetic_athlete():
    m = E.fit(road() + trails(), AET, method="history")
    assert m.v_flat_kmh == pytest.approx(V)
    t = m.modes["trail"]
    assert t.method == "history" and t.vam_mh == pytest.approx(VAM, rel=1e-6)
    assert t.density_range == [50, round((150 + 70 * 7) / 10)]


def test_backtest_is_exact_on_noise_free_data_and_reports_error_with_noise():
    bt = E.backtest(road() + trails(), AET)["trail"]
    assert bt["n"] == 8 and bt["mae_min"] == pytest.approx(0.0, abs=0.1) and not bt["estimate"]
    assert bt["history"]["mape_pct"] == pytest.approx(0.0, abs=0.1)
    assert bt["ep"]["mape_pct"] > bt["history"]["mape_pct"]            # EP is not the true model here
    assert bt["method"] == "history"                                   # auto picks the better one
    noisy = E.backtest(road() + trails(noise=0.3, n=10), AET)["trail"]
    assert noisy["mape_pct"] > 3.0 and len(noisy["rows"]) == 10
    assert all(r["pred_min"] > 0 for r in noisy["rows"])


def test_auto_picks_ep_when_ep_predicts_better():
    # samples generated by EP at 6 km-effort/h: EP must win the inner LOO
    ss = [E.Sample(f"2026-08-{i + 1:02d}", "trail", 3.0 + i, 100.0 * i + 90, 100.0 * i + 90,
                   (3.0 + i + (100.0 * i + 90) / 100.0) / 6.0 * 60.0, 130.0) for i in range(7)]
    m = E.fit(road() + ss, AET)
    assert m.modes["trail"].method == "ep" and m.modes["trail"].ep_kmh == pytest.approx(6.0)


def test_exactly_min_samples_needs_backtest_evidence_for_history():
    # 5 samples: every inner fold has 4 and can't fit history -> no evidence -> EP
    m = E.fit(road() + trails(n=E.MIN_SAMPLES), AET)
    assert m.modes["trail"].method == "ep"
    assert E.fit(road() + trails(n=E.MIN_SAMPLES + 1), AET).modes["trail"].method == "history"


def test_fewer_than_min_samples_fall_back_to_ep():
    m = E.fit(road() + trails(n=E.MIN_SAMPLES - 1), AET)
    t = m.modes["trail"]
    assert t.method == "ep" and t.n == E.MIN_SAMPLES - 1
    h = m.modes["hike"]
    assert h.method == "ep" and h.n == 0 and h.ep_kmh == pytest.approx(t.ep_kmh)   # pooled trail speed
    bt = E.backtest(road() + trails(n=3), AET)
    assert bt["hike"]["n"] == 0 and bt["hike"]["estimate"]              # nothing to backtest -> 推估


def test_hike_two_parameter_fit():
    hv, hvam = 4.5, 450.0
    ss = [E.Sample(f"2026-05-{i + 1:02d}", "hike", 5.0 + 3 * i, 300.0 + 250 * i, 300.0 + 250 * i,
                   ((5 + 3 * i) / hv + (300 + 250 * i) / hvam + E.descent_hours(5 + 3 * i, 300 + 250 * i, 300 + 250 * i)) * 60,
                   110.0) for i in range(6)]
    h = E.fit(road() + ss, AET, method="history").modes["hike"]
    assert h.method == "history"
    assert h.v_flat_kmh == pytest.approx(hv, rel=1e-6) and h.vam_mh == pytest.approx(hvam, rel=1e-6)


def test_flat_speed_regression_when_few_easy_road_runs():
    # no run under AeT+3, but a clean speed ~ HR line: speed at AeT
    rs = [E.Sample(f"2026-06-{i + 1:02d}", "road", 5.0, 10.0, 10.0, 5.0 / (6.0 + 0.1 * (hr - AET)) * 60.0, hr)
          for i, hr in enumerate([145, 148, 150, 152, 155, 158, 160, 162])]
    m = E.fit(rs, AET)
    assert m.v_flat_kmh == pytest.approx(6.0, rel=1e-6) and "迴歸" in m.v_flat_source


def test_design_is_the_inverse_of_the_time_model():
    m = E.fit(road() + trails(), AET, method="history")
    for mode in ("trail", "hike", "road"):
        for d in (0, 50, 100, 150):
            out = E.design(m, mode, 60.0, d)
            assert E.predict_hours(m, mode, out["km"], out["km"] * d) * 60 == pytest.approx(60.0, rel=2e-3)
            assert abs(out["gain_m"] - out["km"] * d) <= 1
    road10 = E.design(m, "road", 60, 0)
    assert road10["km"] == pytest.approx(V, rel=1e-3)                   # flat road = km / v_flat
    trail = E.design(m, "trail", 60, 100)
    assert trail["km"] < road10["km"]                                   # same time, less distance with climb


def test_grade_cost_hook():
    m = E.fit(road() + trails(), AET, grade_cost=M.grade_factor)
    flat = E.predict_hours(m, "trail", 10.0, 0.0)
    assert flat == pytest.approx(10.0 / V)
    assert E.predict_hours(m, "trail", 10.0, 1000.0) > flat


def test_api_design(monkeypatch):
    from backend.api import plan_sessions
    ss = road() + trails()
    summ = {"model": E.fit(ss, AET).to_dict(), "backtest": E.backtest(ss, AET), "estimate": {"trail": False, "hike": True}}
    monkeypatch.setattr(plan_sessions, "_equivalence", lambda: summ)
    app = FastAPI()
    app.include_router(plan_sessions.router)
    c = TestClient(app)
    r = c.post("/api/v1/overview/plan/equivalence/design", json={"mode": "trail", "minutes": 60, "climb_per_km": 100})
    assert r.status_code == 200
    b = r.json()
    assert b["km"] == E.design(E.fit(ss, AET), "trail", 60, 100)["km"] and b["estimate"] is False
    assert c.post("/api/v1/overview/plan/equivalence/design", json={"mode": "swim", "minutes": 60}).status_code == 400
    assert c.get("/api/v1/overview/plan/equivalence").json()["backtest"]["trail"]["n"] == 8
