"""The demo's two planned-and-done sessions: an interval workout and a trail run,
each recorded as the athlete ran the session the planner put on the 課表, so the
single-activity view shows the plan side (間歇判讀 against the session's target
band, the 課表 tag on the trail run).

They are made the way the real app links them, nothing is written to a session
by hand:

  1. the 課表 of the anchor's week is generated by the app (GET
     /overview/plan/sessions, as on the first visit);
  2. the two sessions are picked from it — the week's interval session (kind
     quality) and the trail session on the anchor day (山路 / 越野, a climb);
  3. a FIT that follows each session's steps (engine/workout_steps.derive: the
     structure the watch gets) is written into the COROS sync folder and imported
     by file_service.scan_and_import, the code a COROS sync runs;
  4. GET /overview/plan/sessions again: plan_store.match_only pairs the new runs
     with their sessions (the interval run, two days early, by the generator's
     week-wide match; the trail run on its own day) and stores the pairs.

The activities are the newest of the data (the interval in the evening of the day
before the anchor, the trail run on the anchor morning), so every older activity
keeps its index — what lets `python -m backend.demo.build --root X --add-linked`
add them to an existing demo base and backend.demo.export_static --update reuse an
existing static export.
"""
from __future__ import annotations

import datetime as dt
import json
from pathlib import Path
from typing import Optional

import numpy as np

from backend.demo import athlete as A
from backend.demo import fitwrite as FW
from backend.demo import generate as G
from backend.demo import season as S
from backend.demo.signals import Segment, simulate_run

KINDS = ("interval_plan", "trail_plan")
SESSIONS = "/api/v1/overview/plan/sessions"
INTERVAL_HOUR = 18.0           # local start: an evening session
TRAIL_HOUR = 6.0
# the reps of the interval run, as a position in the planned band [lo, hi]: on target,
# the last one fading to just above the band's lower edge (a few 10-s stretches under it)
REP_POS = (0.6, 0.55, 0.65, 0.5)         # reps 1..n-1
LAST_REP = 0.4                           # the last rep
TRAIL_FRAC = 0.72                        # × CP: the trail run, kept under the AeT cap


def _monday(d: dt.date) -> dt.date:
    return d - dt.timedelta(days=d.weekday())


def pick_sessions(sessions: list[dict], anchor: dt.date) -> dict:
    """{kind: (session, activity day, local hour)} from the stored 課表: the interval
    session of the anchor's week still open (done the evening before the anchor, or
    the anchor evening on a Monday), and the open trail session on the anchor day."""
    wk = _monday(anchor)
    open_ = [s for s in sessions if s.get("state") == "active" and s.get("day")
             and _monday(dt.date.fromisoformat(s["day"])) == wk]
    out = {}
    q = sorted((s for s in open_ if s.get("kind") == "quality" and s["day"] >= anchor.isoformat()),
               key=lambda s: s["day"])
    if q:
        day = anchor - dt.timedelta(days=1)
        if _monday(day) != wk:
            day = anchor
        out["interval_plan"] = (q[0], day, INTERVAL_HOUR)

    def trail(s):
        t = s.get("title") or ""
        return s.get("terrain") == "trail" or bool(s.get("climb_m")) or "山路" in t or "越野" in t
    tr = [s for s in open_ if s["day"] == anchor.isoformat() and s.get("kind") in ("long", "easy", "hike")
          and trail(s)]
    if tr:
        out["trail_plan"] = (max(tr, key=lambda s: s.get("minutes") or 0), anchor, TRAIL_HOUR)
    return out


def _secs(st: dict, default: int) -> int:
    d = st.get("dur") or {}
    return int(d.get("value")) if d.get("type") == "time" and d.get("value") else default


def segments(steps: dict, cp: float, small: bool = False) -> list[Segment]:
    """The session's steps (workout_steps format) as run: warm-up / cool-down easy,
    each work step inside its band (REP_POS; the last rep at LAST_REP, a little fade),
    the rests a jog / walk; one lap per step (the watch laps each pushed step)."""
    from backend.engine import workout_steps as WS
    flat = [f["st"] for f in WS.flat(steps.get("items") or [])]
    works = [i for i, st in enumerate(flat) if st.get("kind") == "work"]
    out = []
    k = 0
    for i, st in enumerate(flat):
        tg = st.get("target") or {}
        kind = st.get("kind")
        dur = _secs(st, 600)
        if kind == "work" and tg.get("intent") == "band" and tg.get("lo"):
            lo, hi = float(tg["lo"]), float(tg.get("hi") or tg["lo"] * 1.05)
            last = i == works[-1] and len(works) > 1
            frac = lo + (hi - lo) * (LAST_REP if last else REP_POS[k % len(REP_POS)])
            k += 1
            out.append(Segment(dur, frac, label=f"rep {k}"))
        elif kind == "work" and tg.get("type") == "power" and tg.get("mode") == "abs" and tg.get("lo"):
            out.append(Segment(dur, (float(tg["lo"]) + float(tg.get("hi") or tg["lo"])) / 2 / cp))
        elif kind == "work":
            out.append(Segment(dur, TRAIL_FRAC))
        elif kind == "rest":
            out.append(Segment(dur, 0.50, label="rest"))
        elif kind == "warm":
            out.append(Segment(dur, 0.68))
        else:
            out.append(Segment(dur, 0.62))
    if small:
        out = [Segment(max(30, s.dur_s // 4), s.frac, s.lap, s.fade, s.label) for s in out]
    return out


def build_fit(seed: int, k: int, kind: str, session: dict, day: dt.date, hour: float, cp: float,
              small: bool = False) -> tuple[bytes, dict]:
    """The FIT of one linked session (deterministic: rng (seed, 5, k))."""
    from backend.engine import workout_steps as WS
    rng = G._rng(seed, 5, k)
    steps = session.get("steps") or WS.derive(session)
    if not steps:
        raise ValueError(f"session {session.get('title')!r} has no structure")
    segs = segments(steps, cp, small)
    minutes = sum(s.dur_s for s in segs) / 60.0
    if kind == "interval_plan":
        p = S.Planned(date=day, kind="interval", minutes=minutes, sport="run", name=session.get("title") or "",
                      hour=hour, stryd=True)
        course = G._run_course(rng, p, minutes, small)
        sig = simulate_run(rng, course, segs, cp=cp, stryd=True, doy=day.timetuple().tm_yday, hour=hour,
                           drift=0.05, has_power=True, lock_ok=False, pace_sd=0.012, power_sd=0.02)
        sub = FW.SUB_GENERIC
    else:
        climb = float(session.get("climb_m") or 1200.0)
        p = S.Planned(date=day, kind="trail_long", minutes=minutes, sport="trail", name=session.get("title") or "",
                      hour=hour, stryd=True, params={"climb": climb})
        # held under the AeT cap: little drift (the athlete eases off as it creeps up)
        _, sig = G.trail_run(rng, p, segs, small, cp=cp, stryd=True, doy=day.timetuple().tm_yday, hour=hour,
                             drift=0.01, push=0.05, down_cap=3.2, has_power=True, lock_ok=False)
        sub = FW.SUB_TRAIL
    start = G._local_start(p)
    raw = FW.encode_activity(start=start, lat=sig.lat, lon=sig.lon, alt=sig.alt, dist=sig.dist,
                             speed=sig.speed, hr=sig.hr, cadence=sig.cadence, power=sig.power, temp=sig.temp,
                             stryd=True, laps=sig.laps, sport=FW.SPORT_RUNNING, sub_sport=sub,
                             total_ascent=sig.ascent, total_descent=sig.descent, form_power=sig.form_power,
                             air_power=sig.air_power, lss=sig.lss)
    hr = sig.hr[np.isfinite(sig.hr)]
    info = {"start_utc": start.strftime("%Y-%m-%dT%H:%M:%SZ"), "duration_s": int(sig.n),
            "distance_m": round(float(sig.dist[-1]) if sig.n else 0.0, 1),
            "elevation_gain_m": round(sig.ascent, 1), "sport": p.sport, "kind": kind,
            "name": session.get("title"), "showcase": True, "stryd": True, "date": day.isoformat(),
            "hr_min": float(hr.min()) if len(hr) else None, "hr_max": float(hr.max()) if len(hr) else None,
            "avg_power": round(float(np.mean(sig.power)), 1) if sig.power is not None else None,
            "trip": None, "day": 0, "session": {"title": session.get("title"), "day": session.get("day"),
                                                "kind": session.get("kind")}}
    return raw, info


def _cp_on(base: Path, day: dt.date) -> float:
    """The plan's CP on `day` (what the app evaluates the run against)."""
    from backend.engine.planning import Plan
    try:
        plan = Plan.load(base / "plan.json")
        rows = sorted((t for t in plan.thresholds if t.cp and t.date <= day.isoformat()), key=lambda t: t.date)
        if rows:
            return float(rows[-1].cp)
    except Exception:                       # noqa: BLE001 — the demo's own CP otherwise
        pass
    return float(A.CP_HISTORY[-1])


def _rows(c) -> list[dict]:
    acts = c.get("/api/v1/wko5/workouts").json()
    return acts if isinstance(acts, list) else acts.get("workouts") or []


def add(c, base: Path, manifest: dict, anchor: dt.date, seed: int, small: bool = False, log=print) -> list[dict]:
    """Add the linked sessions' activities to the base the TestClient `c` (owner mode,
    WKO5COACH_HOME = base) serves; updates `manifest` (activities, showcase). Returns
    the new activity rows ([] when they are there already or the 課表 has no such session)."""
    if any(a.get("kind") in KINDS for a in manifest.get("activities") or []):
        log("  linked sessions: already in this base")
        return []
    r = c.get(SESSIONS)
    if r.status_code != 200:
        log(f"  ! linked sessions: {SESSIONS} {r.status_code}")
        return []
    picks = pick_sessions(r.json().get("sessions") or [], anchor)
    if not picks:
        log("  linked sessions: no interval / trail session open in the anchor's week")
        return []
    n0 = len(manifest.get("activities") or [])
    new = []
    for k, kind in enumerate(KINDS, start=1):
        if kind not in picks:
            log(f"  linked sessions: no {kind} session")
            continue
        s, day, hour = picks[kind]
        raw, info = build_fit(seed, k, kind, s, day, hour, _cp_on(base, day), small)
        d = base / "fit" / "coros" / str(day.year)
        d.mkdir(parents=True, exist_ok=True)
        f = d / f"demo_{n0 + k:04d}.fit"
        f.write_bytes(raw)
        info["file"] = f.relative_to(base).as_posix()
        new.append(info)
    if not new:
        return []
    before = {Path(str(x.get("file", ""))).name: x.get("index") for x in _rows(c)}

    async def imp():
        from backend.db import database
        from backend.files.file_service import scan_and_import
        async with database.AsyncSessionLocal() as db:
            return await scan_and_import(db, 1, str(base / "fit"))
    log(f"  linked sessions: imported {c.portal.call(imp)}")
    rows = _rows(c)
    by_file = {Path(str(x.get("file", ""))).name: x for x in rows if "index" in x}
    for a in new:
        x = by_file.get(Path(a["file"]).name)
        if x is None:
            log(f"  ! linked sessions: {a['file']} not imported")
            continue
        a["index"] = x["index"]
        # the watch names a run after the pushed workout
        c.patch(f"/api/v1/wko5/workouts/{x['index']}/activity", json={"name": a["name"]})
    # the sync's next page view: plan_match pairs the runs with their sessions (stored)
    ss = c.get(SESSIONS).json().get("sessions") or []
    for a in new:
        hit = next((s for s in ss if s.get("state") == "done" and (s.get("done_by") or {}).get("index") == a.get("index")), None)
        a["linked"] = {"uid": hit["uid"], "title": hit["title"], "match": hit["done_by"].get("match")} if hit else None
        log(f"  linked sessions: {a['kind']} {a['date']} #{a.get('index')} -> "
            f"{(hit or {}).get('title', '(not matched)')} ({((hit or {}).get('done_by') or {}).get('match')})")
    moved = [n for n, i in before.items() if (by_file.get(n) or {}).get("index") != i]
    if moved:
        # the static export's --update reuses every older activity's files by index
        log(f"  ! linked sessions: {len(moved)} older activities changed index (e.g. {moved[:3]})")
    for a in new:
        a.pop("index", None)
        manifest.setdefault("activities", []).append(a)
        manifest.setdefault("showcase", {})[a["kind"]] = a["file"]
        manifest.setdefault("files", {})[a["file"]] = G._sha((base / a["file"]).read_bytes())
    manifest["n_activities"] = len(manifest["activities"])
    return new


def rewrite_trail(c, base: Path, manifest: dict, seed: int, small: bool = False, log=print) -> Optional[str]:
    """Re-write the linked trail run's FIT in place (build_fit with the current
    generator) from its stored 課表 session; updates its manifest entry. Returns the
    FIT path (relative to `base`) or None (no linked trail run in this base). The
    caller re-imports it (build.reimport)."""
    i, a = next(((i, a) for i, a in enumerate(manifest.get("activities") or []) if a.get("kind") == "trail_plan"),
                (None, None))
    if a is None:
        return None
    uid = (a.get("linked") or {}).get("uid")
    day = dt.date.fromisoformat(a["date"])
    ss = c.get(SESSIONS, params={"scope": "week", "day": day.isoformat()}).json().get("sessions") or []
    s = next((x for x in ss if uid and x.get("uid") == uid), None) or \
        next((x for x in ss if x.get("title") == (a.get("session") or {}).get("title")
              and x.get("day") == (a.get("session") or {}).get("day")), None)
    if s is None:
        log(f"  ! linked trail run: its session ({uid}) is not in the 課表 any more")
        return None
    k = KINDS.index("trail_plan") + 1
    raw, info = build_fit(seed, k, "trail_plan", s, day, TRAIL_HOUR, _cp_on(base, day), small)
    (base / a["file"]).write_bytes(raw)
    for key in ("file", "linked"):
        if key in a:
            info[key] = a[key]
    manifest["activities"][i] = info
    manifest.setdefault("files", {})[a["file"]] = G._sha(raw)
    return a["file"]


def stage(base: Path, anchor: Optional[dt.date], seed: Optional[int], warm: bool = True) -> None:
    """--add-linked, in the child process (owner mode on the base): add the two linked
    sessions to an existing base and warm what they change."""
    import time
    from fastapi.testclient import TestClient
    from backend.demo import build as B
    from backend.main import build_app
    mp = base / "demo_manifest.json"
    manifest = json.loads(mp.read_text("utf-8"))
    anchor = anchor or dt.date.fromisoformat(manifest["anchor"])
    seed = seed if seed is not None else int(manifest.get("seed") or B.DEFAULT_SEED)
    t0 = time.time()
    with TestClient(build_app(demo=False), raise_server_exceptions=False) as c:
        new = add(c, base, manifest, anchor, seed, small=bool(manifest.get("small")))
        print(f"  linked: {time.time() - t0:.0f} s", flush=True)
        if new and warm:
            B.warm_base(c, anchor, [a["file"] for a in new], charts_for=len(new))
    mp.write_text(json.dumps(manifest, ensure_ascii=False, indent=1), "utf-8")
